TOPDIR=			..
include $(TOPDIR)/os.mk

LIB=			einfo
SHLIB_MAJOR=	1
SRCS=			libeinfo.c
INCS=			einfo.h
VERSION_MAP=	einfo.map

SHLIBDIR=		/${LIBNAME}

include $(TOPDIR)/cc.mk
include $(TOPDIR)/lib.mk
include $(TOPDIR)/$(TERMCAP).mk
