.TH "OPENRC" "8" "Nov 2007" "openrc" "openrc"
.SH NAME
rc-status \- show status info about runlevels
.SH SYNOPSIS
\fBrc-status\fR \fI[command [runlevel]]\fR
.SH DESCRIPTION
\fBrc-status\fR gathers and displays information about the status of init 
scripts in different runlevels.  The default behavior is to show information 
about the current runlevel, but any runlevel can be quickly examined.
directory.  They must also conform to the OpenRC runscript standard.
.SH OPTIONS
.TP
\fB\-\-all (\-a)\fR
Show all runlevels and their services
.TP
\fB\-\-list (\-l)\fR
List all defined runlevels
.TP
\fB\-\-nocolor (\-nc)\fR
Disable color output
.TP
\fB\-\-servicelist (\-s)\fR
Show all services
.TP
\fB\-\-unused (\-u)\fR
Show services not assigned to any runlevel
.TP
\fB[runlevel]\fR
Show information only for the named \fBrunlevel\fR
.SH "SEE ALSO"
.BR rc-update (8)
.SH AUTHORS
Mike Frysinger <vapier@gentoo.org>
