#!/bin/sh
# Copyright 2006-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Ensure we are called by init
[ "$PPID" = "1" ] || exit 0

# If $TERM is not set then assume default of cons25
# This gives us a nice colour boot :)
[ -z "$TERM" ] && export TERM="cons25"

# BSD's init works somewhat differently to sysvinit.
# This block should 'translate' from the way init calls it to the way it would
# be called by sysvinit on linux.
RUNLEVEL="1" /sbin/rc sysinit || exit 1
RUNLEVEL="1" /sbin/rc boot || exit 1
PREVLEVEL="1" /sbin/rc default

# If we return non zero after starting rc then 2 things may happen
# 1) We get the message "init: can't get /dev/console for controlling terminal"
#    every few seconds
# 2) We get no error and console freezes.
# This is probably a bug somewhere in rc, but until that is fixed we have to
# return 0.
exit 0
