#!/bin/sh
# Copyright 2006-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Ensure we are called by init
[ "$PPID" = "1" ] || exit 0

# If $TERM is not set then assume default of cons25
# This gives us a nice colour boot :)
[ -z "$TERM" -o "$TERM" = "dumb" ] && export TERM="cons25"

# Handle interupts 
trap : SIGINT
trap "echo 'Boot interrupted'; exit 1" SIGQUIT

# BSD's init works somewhat differently to sysvinit.
# This block should 'translate' from the way init calls it to the way it would
# be called by sysvinit on linux.
RUNLEVEL="1" /sbin/rc sysinit || exit 1
RUNLEVEL="1" /sbin/rc boot || exit 1
PREVLEVEL="1" /sbin/rc default

# We don't actually care if rc default worked or not, we should exit 0
# to allow logins
exit 0
