NET_LO=	net.lo

SRCS+=	devfs.in dmesg.in hwclock.in consolefont.in keymaps.in modules.in \
	mtab.in numlock.in procfs.in sysfs.in termencoding.in

.SUFFIXES:	.Linux.in
.Linux.in:
	sed ${SED_REPLACE} ${SED_EXTRA} $< > $@
