# Generic BSD scripts
SRCS+=	hostid.in moused.in newsyslog.in pf.in rarpd.in rc-enabled.in \
	rpcbind.in savecore.in sysctl.in syslogd.in

# These are NetBSD specific
SRCS+=	swap-blk.in ttys.in wscons.in
