name: ci_alpine_linux

on: [push, pull_request]

jobs:

  alpine:
    name: Alpine Linux
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - run: >-
          apk --no-cache add \
            build-base \
            meson \
            pkgconf \
            linux-pam \
            linux-pam-dev \
            libcap \
            libcap-dev
      - uses: actions/checkout@v2
      - run: meson setup builddir/
      - run: meson compile -C builddir
      - run: meson test --verbose -C builddir
