# Nabbed from https://github.com/mesonbuild/meson/blob/master/docs/markdown/Continuous-Integration.md#github-actions
name: ci_meson

on: [push, pull_request]

jobs:

  linux-gcc-glibc-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update -q
    - run: sudo apt-get install -q -y build-essential libpam-dev meson
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: ninja -C builddir
      env:
        CC: gcc


  linux-clang-glibc-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update -q
    - run: sudo apt-get install -q -y build-essential clang libpam-dev meson
    - run: meson setup builddir/
      env:
        CC: clang
    - run: ninja -C builddir
      env:
        CC: clang


  linux-gcc-alpine-musl:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: install deps
        run: >-
          apk --no-cache add \
            build-base \
            meson \
            pkgconf \
            linux-pam \
            linux-pam-dev
      - name: checkout
        uses: actions/checkout@v2
      - run: meson setup builddir/
        env:
          CC: gcc
      - run: ninja -C builddir
        env:
          CC: gcc
