# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/openrc-openrc
name: Coverity Scan

on:
  push:
    branches: [master]

jobs:
  secrets:
    runs-on: ubuntu-latest
    outputs:
      HAS_SCAN_EMAIL: ${{ steps.check.output.HAS_SCAN_EMAIL }}
      HAS_SCAN_TOKEN: ${{ steps.check.output.HAS_SCAN_TOKEN }}
    steps:
      - run: >
          echo "::set-output name=HAS_SCAN_EMAIL::${{ env.COVERITY_SCAN_EMAIL != '' }}";
          echo "::set-output name=HAS_SCAN_TOKEN::${{ env.COVERITY_SCAN_TOKEN != '' }}";
        id: check
        env:
          COVERITY_SCAN_EMAIL: ${{ secrets.COVERITY_SCAN_EMAIL }}
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

  coverity:
    runs-on: ubuntu-latest
    needs: ["secrets"]
    if: >
      needs.secrets.outputs.HAS_SCAN_EMAIL == 'true' &&
      needs.secrets.outputs.HAS_SCAN_TOKEN == 'true'
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update -q
    - run: sudo apt-get install -q -y build-essential libpam-dev meson libcap-dev
    - run: meson setup builddir/
      env:
        CC: gcc
    - uses: vapier/coverity-scan-action@v1
      with:
        command: ninja -C builddir
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
